### ISSUE TITLE
 Hi, dude, could you help me? when trying to run this project I have the following error in android studio

### ISSUE THREAD

**Issue by rodrigogivisiez** [fesskiev/MediaCenter2#1]
12:04	Unsupported Modules Detected: Compilation is not supported for following modules: MediaCenter2. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

**Comment by fesskiev** [comment]
Hi, I think this link will help you
https://stackoverflow.com/questions/28668252/android-studio-error-unsupported-modules-detected-compilation-is-not-supported

ср, 4 июл. 2018 г. в 18:11, rodrigo2017 <notifications@github.com>:

**Comment by rodrigogivisiez** [comment]
Thanks, some attempts and updating of android studio worked perfectly :). You're doing a great job. I'm going to study the project. Use the mini battery pad with the Superpowered Harness Recorder. I will follow and learn from your project, and God willing to contribute. See you.
